import React from "react";

function SpringBoot() {
  return <div>SpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBootSpringBoot</div>;
}

export default SpringBoot;
